[2022-07-27 19:38:19,650] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dataquality_pipeline_v3.add_upload_date__1 manual__2022-07-27T19:38:15.752277+00:00 [queued]>
[2022-07-27 19:38:19,663] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dataquality_pipeline_v3.add_upload_date__1 manual__2022-07-27T19:38:15.752277+00:00 [queued]>
[2022-07-27 19:38:19,663] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 19:38:19,663] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-27 19:38:19,663] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 19:38:19,686] {taskinstance.py:1397} INFO - Executing <Task(_PythonDecoratedOperator): add_upload_date__1> on 2022-07-27 19:38:15.752277+00:00
[2022-07-27 19:38:19,695] {standard_task_runner.py:52} INFO - Started process 10270 to run task
[2022-07-27 19:38:19,706] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dataquality_pipeline_v3', 'add_upload_date__1', 'manual__2022-07-27T19:38:15.752277+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/dataquality_pipeline_v3.py', '--cfg-path', '/tmp/tmp3sfd_awg', '--error-file', '/tmp/tmp1396qzpr']
[2022-07-27 19:38:19,708] {standard_task_runner.py:80} INFO - Job 162: Subtask add_upload_date__1
[2022-07-27 19:38:19,817] {task_command.py:371} INFO - Running <TaskInstance: dataquality_pipeline_v3.add_upload_date__1 manual__2022-07-27T19:38:15.752277+00:00 [running]> on host 2c2de32fb47f
[2022-07-27 19:38:19,945] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=abin404@yopmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dataquality_pipeline_v3
AIRFLOW_CTX_TASK_ID=add_upload_date__1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-27T19:38:15.752277+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-27T19:38:15.752277+00:00
[2022-07-27 19:38:19,952] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dataquality_pipeline_v3.py", line 51, in add_upload_date
    infer_datetime_format=True
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 156, in __init__
    self._validate_parse_dates_presence(self.names)  # type: ignore[has-type]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 277, in _validate_parse_dates_presence
    f"Missing column provided to 'parse_dates': '{missing_cols}'"
ValueError: Missing column provided to 'parse_dates': 'pickup_datetime'
[2022-07-27 19:38:19,962] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dataquality_pipeline_v3, task_id=add_upload_date__1, execution_date=20220727T193815, start_date=20220727T193819, end_date=20220727T193819
[2022-07-27 19:38:19,977] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:119: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2022-07-27 19:38:19,977] {email.py:228} INFO - Email alerting: attempt 1
[2022-07-27 19:38:20,687] {email.py:240} INFO - Sent an alert email to ['abin404@yopmail.com']
[2022-07-27 19:38:22,150] {standard_task_runner.py:97} ERROR - Failed to execute job 162 for task add_upload_date__1 (Missing column provided to 'parse_dates': 'pickup_datetime'; 10270)
[2022-07-27 19:38:22,175] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-27 19:38:22,268] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
